# Generated by Django 4.0.3 on 2022-04-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_poll_result_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
