# Generated by Django 4.0.3 on 2022-05-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_poll_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_ip_addresses', to='vote.poll')),
            ],
        ),
    ]
